### ISSUE TITLE
Flyme6.2.5.0A 微信6.6.1 闪退

### ISSUE THREAD

**Issue by Bylant** [Blankeer/MDWechat#10]
1.7.3版本的MDWchat在Flyme6.2.5.0A 微信6.6.1 环境下 闪退

**Comment by Blankeer** [comment]
请检查是否授予 存储空间 权限,检查在 /sdcard/mdwechat/ 目录下是否有文件

**Comment by Bylant** [comment]
存储空间权限有的  mdwechat目录下也有文件 详情我放到附件截图了  有时间的话请查收  谢谢🤓🤓


来自 魅蓝 Note5

-------- 原始邮件 --------
发件人：Blankeer <notifications@github.com>
时间：周日 1月21日 10:16
收件人：Blankeer/MDWechat <MDWechat@noreply.github.com>
抄送：Bylant <18809428954@163.com>,Author <author@noreply.github.com>
主题：Re: [Blankeer/MDWechat] Flyme6.2.5.0A 微信6.6.1 闪退 (#10)
