### ISSUE TITLE
希望适配微信6.6.3

### ISSUE THREAD

**Issue by lly2016** [Blankeer/MDWechat#12]
微信6.6.3无效，重置版本信息也不行，用习惯了才发现之前的微信太丑了，谢谢大大！

**Comment by WhitLor** [comment]
估计过年作者挺忙，同希望适配新版

**Comment by Blankeer** [comment]
据酷安评论区教程,将 6.6.2.config 复制重命名为 6.6.3.config 就可以了,说明6.6.3至少是大部分代码没变的.我是懒得更新,之后再更吧.😬

**Comment by lly2016** [comment]
楼上正解
