### ISSUE TITLE
actionbar上的搜索按钮点击后无法输入

### ISSUE THREAD

**Issue by KempLeung** [Blankeer/MDWechat#13]
actionbar上的搜索按钮点击后无法输入
使用环境 ：一加5T lineageos15.1 官方0305夜版 magiak16.0+xposed 90.1beta3 systemless 输入法为gboard beta版

**Comment by Blankeer** [comment]
这是一个已知的问题,😂

**Comment by Blankeer** [comment]
[FIXED](https://github.com/Blankeer/MDWechat/commit/38659a976d2ba740c2584f655ae0fc482e1af94f)

**Comment by edison0354** [comment]
Play Store上的6.6.2，似乎搜索框还是无法输入东西。
MDWechat是1.9.0，重置配置文件+去勾打勾+重启，两遍了还是不行……
