### ISSUE TITLE
[bug]搜索框只能输入英文/点击消息Tab无法跳转到未读消息

### ISSUE THREAD

**Issue by amnextking** [Blankeer/MDWechat#14]
手机：一加5
Android：7.1.1
问题有两个：
1.点搜索框只能输入英文，搜索之后跳转的界面才能输入中文。
2.微信原本的消息Tab每点击一次可以依次将未读消息滑动到当前界面最顶上，此功能失效。
感谢你的付出，做出这样好用的插件。

**Comment by Blankeer** [comment]
1.新版本已经修复
2.已知问题,还没加入
