### ISSUE TITLE
TabLayout图标显示问题。

### ISSUE THREAD

**Issue by ProfessionalMe** [Blankeer/MDWechat#15]
当修改了TabLayout上面的图标时，未选中Tab的页面图标显示正常，已选中Tab的页面的图标只会显示图标的轮廓图，背景为白色。我用的是彩色的图标，说白了 就是选中Tab的时候，当前页的图标会变白。
手机品牌:ZUK Z2
Android版本:6.0.1

**Comment by Blankeer** [comment]
按照 md 规范，不会考虑彩色图片的情况。
