### ISSUE TITLE
微信6.6.6悬浮按钮搜索功能失效

### ISSUE THREAD

**Issue by EvilZabanya** [Blankeer/MDWechat#19]
MD1.9.0，微信6.6.6
修改了悬浮按钮，在微信6.6.5下正常，按悬浮按钮弹出搜索按钮，点击后进入微信自身的搜索界面。
更新到MD1.9.0+微信6.6.6后搜索按钮点击后没反应，MD替换的搜索也搜不了东西，输入以后字打进去了但是没反应。
感谢作者的努力，这软件用了完全停不下来~

**Comment by EvilZabanya** [comment]
刚刚又试了一下，现在我的做法是隐藏actionbar和搜索 两个选项都关闭，可以用自带搜索。
开启搜索，可以输入中文，无法输入数字，无法退格键删除，按回车没有任何反应。

**Comment by Blankeer** [comment]
目前正在写新版本，这些问题都可以解决，还在写。。。。🙄

**Comment by EvilZabanya** [comment]
感谢大佬，手动五体投地

**Comment by Blankeer** [comment]
2.0.0 测试版已去掉搜索魔改。。
