### ISSUE TITLE
pixel play版6.6.6无效

### ISSUE THREAD

**Issue by SerenadeHL** [Blankeer/MDWechat#20]
12467): WeChatFp [initWechat](WalletBaseUI.java:51) loaded: [com.tencent.mm] version:3.6.0
05-24 07:49:41.824 I/Xposed  (12467): WeChatFp [beforeHookedMethod](WalletBaseUI.java:55) Application onCreate
05-24 07:49:41.824 I/Xposed  (12467): WeChatFp [main](XposedWeChatPlugin.java:73) Xposed plugin init version: 3.6.0
05-24 07:49:41.839 I/Xposed  (12467): WeChatFp [main](XposedWeChatPlugin.java:78) WeChat Version code:1283
05-24 07:49:41.883 I/Xposed  (12467): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:95) Activity onResume =	com.tencent.mm.splash.i@b71c68a	
05-24 07:49:42.395 I/Xposed  (12467): WeChatFp [beforeHookedMethod](XposedWeChatPlugin.java:95) Activity onResume =	com.tencent.mm.app.WeChatSplashActivity@65d0c2d	
05-24 07:49:42.804 I/Xposed  (12538): MDWechat:	wechat version=6.6.6,processName=com.tencent.mm:exdevice,MDWechat version=1.9.0	ts=1527119382804
05-24 07:49:42.812 I/Xposed  (12538): MDWechat:	不支持的版本:6.6.6	ts=1527119382812

**Comment by Blankeer** [comment]
play 6.6.6 暂未支持

**Comment by YandexStudio** [comment]
什么时候能适配呢？
