### ISSUE TITLE
目前均发现的BUG

### ISSUE THREAD

**Issue by 244276041** [Blankeer/MDWechat#27]
目前均发现的BUG
1.联系人界面北京替换失效
2.零钱界面的顶部为白色，看不清
3.气泡不能替换语音 对方跟自己都替换不了
4.订阅号，公众号是不是可以添加图片进去呢？
我使用的是小米5S

**Comment by Blankeer** [comment]
请按照 [issue 提交模板](https://github.com/Blankeer/MDWechat/issues/new?template=bug_report.md)重新提交，谢谢
