### ISSUE TITLE
微信6.6.7在OnePlus 3T上悬浮按钮不能使用

### ISSUE THREAD

**Issue by Mushroom51163** [Blankeer/MDWechat#29]
功能点进去没有反应

**Comment by Blankeer** [comment]
请按照 [issue 提交模板](https://github.com/Blankeer/MDWechat/issues/new?template=bug_report.md)重新提交，谢谢

**Comment by MSClico** [comment]
这个问题作者大大有在说明文档中提及，自己用 开发者助手 获取你要实现的控件的Activity类名，然后打开mdwechat-view-floatbutton.txt，将type：“…”中的引号里面的内容替换为你获取到的Activity类名就可以了。
举例，我获取的play版6.67各控件Activity类名有：
1.收付款：com.tencent.mm.plugin.mall.ui.MallIndexUI
2.扫一扫：com.tencent.mm.plugin.scanner.ui.BaseScanUI
3.搜索：
com.tencent.mm.plugin.fts.ui.FTSMainUI
4.添加好友：com.tencent.mm.plugin.subapp.ui.pluginapp.AddMoreFriendsUI
