### ISSUE TITLE
6.6.7+里的右下角:收付款、扫一扫、群聊、添加好友都用不了，说:转跳失败请检查类名是否正确

### ISSUE THREAD

**Issue by easyinplay** [Blankeer/MDWechat#33]
**bug 描述**
6.6.7+里的右下角:收付款、扫一扫、群聊、添加好友都用不了，说:转跳失败请检查类名是否正确

**环境**
1. Android 版本 7.1
2. 机型 oneplus3t
3. MDWechat 版本 2.0
4. Xposed 环境及版本 magisk中的 89
5. 微信版本 6.67

**复现步骤**
1. 进入主界面
2. 点击 右下角➕
3. 出现 以上 现象

**期望**
描述期望的结果

**截图**
截图

**日志(可选)**
日志

**其他说明**

**Comment by Blankeer** [comment]
type 需要是完整 Activity 类名，可以借助开发者助手或 auto.js 等工具查看

**Comment by 164738777** [comment]
+1, 也遇到这个问题, cool1 dual, Android 6.0.1, wechat 6.6.7

---2018年8月30日12:47:11

已根据楼下老哥的提示修改了txt, 成功设置~

**Comment by MSClico** [comment]
这个问题作者大大有在说明文档中提及，自己用 开发者助手 获取你要实现的控件的Activity类名，然后打开mdwechat-view-floatbutton.txt，将type：“…”中的引号里面的内容替换为你获取到的Activity类名就可以了。
举例，我获取的play版6.67各控件Activity类名有：
1.收付款：com.tencent.mm.plugin.mall.ui.MallIndexUI
2.扫一扫：com.tencent.mm.plugin.scanner.ui.BaseScanUI
3.搜索：
com.tencent.mm.plugin.fts.ui.FTSMainUI
4.添加好友：com.tencent.mm.plugin.subapp.ui.pluginapp.AddMoreFriendsUI
