### ISSUE TITLE
Virtual Xposed下悬浮按钮无法隐藏

### ISSUE THREAD

**Issue by lxx19970628a** [Blankeer/MDWechat#34]
请按以下步骤填写，不规范的 issue 会被关闭
**bug 描述**
悬浮按钮无法隐藏

**环境**
1. Android 版本 6.0.1
2. 机型 Blackberry Priv
3. MDWechat 版本 2.0beta
4. Xposed 环境及版本 Virtual Xposed 0.12.7 Xposed 91
5. 微信版本 6.6.7 play

**复现步骤**

因为adb改了分辨率和dpi，所以图标都变得很大，再加上自己没弄明白转向连接，就索性想把悬浮窗取消掉，但是现在并不能。

**Comment by Blankeer** [comment]
3.1.0 已修复
