### ISSUE TITLE
最新版2.0.1不支持微信6.7.2…

### ISSUE THREAD

**Issue by Darkpurple** [Blankeer/MDWechat#36]
我發現更新了微信6.7.2之後再更新2.0.1無法自動適配…一打開微信就會…錯誤關閉…

我使用以下兩部手機有同樣問題：

环境（一）

Android 版本8.0
机型 Samsung S8
MDWechat 版本 2.0.1beta
Xposed 环境及版本 90.2beta3
微信版本 6.7.2

环境（二）

Android 版本8.1
机型 Oneplus 6
MDWechat 版本 2.0.1beta
Xposed 环境及版本 90.2beta3
微信版本 6.7.2

**Comment by JasonKhew96** [comment]
安卓8好像不能，我的也闪退，XP的问题
`https://github.com/rovo89/Xposed/issues/325`

**Comment by whyou** [comment]
多问一句，你们有试过微信6.67版本么？是否也有同样问题？

**Comment by Darkpurple** [comment]
我用6.6.7時+2.0.0版本時是沒問題的...

**Comment by luoweij** [comment]
我的一直卡黑屏、进不去

**Comment by ghost** [comment]
同样黑屏进不去

**Comment by Blankeer** [comment]
2.x 版本暂停维护，3.x 版本正常
