### ISSUE TITLE
圆角头像无效

### ISSUE THREAD

**Issue by ckyun06** [Blankeer/MDWechat#38]
**环境**
1. Android 版本 7.0
2. 机型LG G5
3. MDWechat 版本2.0.1beta
4. Xposed 环境及版本xposed8.9.3 （magisk)
5. 微信版本 6.6.7 / 6.7.2

**复现步骤**
1. MDwechat设置开启圆角头像后打开微信头像并未变成圆角

**Comment by Blankeer** [comment]
已修复
