### ISSUE TITLE
微信6.6.7PLAY版，没有效果

### ISSUE THREAD

**Issue by zhangyq926** [Blankeer/MDWechat#39]
安装，XPOSED中勾选模块，重新生成配置，重启，以上三个动作做了好几次，都没效果，总开关缺省打开的

**Comment by zhangyq926** [comment]
补充：
手机：一加6
安卓：8.1
XPOSED： magdisk xposed 
微信：play版6.6.7

**Comment by vlt23** [comment]
我这边刚开始微信也会闪退。但是把微信强制停止了之后再打开就没问题了。。。
手机：小米5 -- LOS15.1（Android 8.1)
Xposed：90-beta3（官方rovo的）
微信：play 6.6.7
MDWechat：3.0.0

**Comment by sakuyamaij** [comment]
一加5T
Magisk+Xposed Systemless(90.2-beta3)
微信：play 6.6.7
MDWechat：3.0.0

同样毫无效果

**Comment by Blankeer** [comment]
1.按照升级指南重试
2.检查配置文件是否生成成功
3.提交日志

**Comment by zhangyq926** [comment]
1.按照升级方法重做了一遍
2.在mdwechat/config/wechat生成了6.6.7.config，但文件内容有点与其他都不一致，见附件
3.打开日志，在mdwechat下没有logs目录
4.打开日志后，重启微信，微信闪退没法正常使用了

[6.6.7.config.txt](https://github.com/Blankeer/MDWechat/files/2377458/6.6.7.config.txt)

**Comment by MSClico** [comment]
play版6.67+magisk xposed89.3+MDwechat3.0
实测没有任何问题，会闪退好像是改了聊天气泡的原因

**Comment by zhangyq926** [comment]
> 
> 
> play版6.67+magisk xposed89.3+MDwechat3.0
> 实测没有任何问题，会闪退好像是改了聊天气泡的原因

我的是PLAY版6.6.7 + magisk + xposed systemless 90.2.beta3 + MDwechat 3.0
怎么试都没效果，打开日志记录微信闪退了

**Comment by MSClico** [comment]
> > play版6.67+magisk xposed89.3+MDwechat3.0
> > 实测没有任何问题，会闪退好像是改了聊天气泡的原因
> 
> 我的是PLAY版6.6.7 + magisk + xposed systemless 90.2.beta3 + MDwechat 3.0
> 怎么试都没效果，打开日志记录微信闪退了

我一开始升级到3.0的时候也没用，退回到2.01发现圆角功能失效了，然后干脆把目录里面的相关文件全部删除了，重新安装3.0，点击生成配置，OK了。也许你也可以这样试下，不担保能成功。

**Comment by zhangyq926** [comment]
> 
> 
> > > play版6.67+magisk xposed89.3+MDwechat3.0
> > > 实测没有任何问题，会闪退好像是改了聊天气泡的原因
> > 
> > 
> > 我的是PLAY版6.6.7 + magisk + xposed systemless 90.2.beta3 + MDwechat 3.0
> > 怎么试都没效果，打开日志记录微信闪退了
> 
> 我一开始升级到3.0的时候也没用，退回到2.01发现圆角功能失效了，然后干脆把目录里面的相关文件全部删除了，重新安装3.0，点击生成配置，OK了。也许你也可以这样试下，不担保能成功。

全部删除了，应用后重启，还是没有效果~~~

**Comment by jw8013** [comment]
> 一加5T
> Magisk+Xposed Systemless(90.2-beta3)
> 微信：play 6.6.7
> MDWechat：3.0.0
> 
> 同样毫无效果
> 红米Note4X
> Magisk+Xposed Systemless(90.2-beta3)
> 微信：play 6.6.7
> MDWechat：3.1.0
> 
> 依旧无效果

**Comment by edison0354** [comment]
同，Play版6.6.7+magisk xposed+Android 8.1，之前2.x的时候还好好的

目录删过了，打勾+开关重启无数遍，还是不行，由于压根就没生效，所以也没有log

试过删掉重启重装生成配置再重启，也无效……

另外我装了WeXposed，不会是冲突吧？

**Comment by Blankeer** [comment]
既然你都发现有问题了，为什么不禁用其他模块试试，请严格按照升级指南步骤来，检查生成配置文件是否成功。另外，play 好像有点问题，未测试

**Comment by edison0354** [comment]
试过禁用WeXposed了，还是无效……应该不是冲突

**Comment by Blankeer** [comment]
1.生成配置文件是否成功
2.提交日志

**Comment by Blankeer** [comment]
> 补充：
> 手机：一加 6
> 安卓：8.1
> XPOSED： magdisk xposed
> 微信：play 版 6.6.7

配置文件以及生成成功了，请打开mdwechat 底部日志选项，然后按照提示获取日志。或者直接导出xp 框架日志

**Comment by edison0354** [comment]
配置文件显示生成成功了，但是似乎有点奇怪？
打开日志选项运行之后也没日志，文件夹都没有……

PS. 后缀.config传不上来改成了log

[xposed_error_20180913_202249.log](https://github.com/Blankeer/MDWechat/files/2379247/xposed_error_20180913_202249.log)

[6.6.7.log](https://github.com/Blankeer/MDWechat/files/2379251/6.6.7.log)

**Comment by Blankeer** [comment]
日志没什么有用的信息。
我刚试了下play 6.6.7版本，3.1.0使用完全正常

**Comment by jw8013** [comment]
> 日志没什么有用的信息。
> 我刚试了下play 6.6.7版本，3.1.0使用完全正常

小米6 安卓7.1.1 play 6.6.7生成配置文件出错，但是用红米NOTE4X AEX8.1  play 6.6.7生成的配置文件OK
但是红米NOTE4X和他们一样打开就闪退，没有任何日志，是不是安卓8.1下有问题啊！

**Comment by jw8013** [comment]
> play版6.67+magisk xposed89.3+MDwechat3.0
> 实测没有任何问题，会闪退好像是改了聊天气泡的原因

你的不是安卓8.1

**Comment by jw8013** [comment]
> 日志没什么有用的信息。
> 我刚试了下play 6.6.7版本，3.1.0使用完全正常

[app.log](https://github.com/Blankeer/MDWechat/files/2381659/app.log)
额，抓了个8.1闪退的包，麻烦大佬看一下

**Comment by Blankeer** [comment]
3.2.0已加入下载共享的适配文件，生成失败的可以尝试
日志记录已正常，可以提交日志文件

**Comment by edison0354** [comment]
Android 8.1
自己生成的和直接下载的配置都试过了，均无效…log也都没有…
我就先留个爪，等等看其他人是什么情况…

**Comment by Blankeer** [comment]
> Android 8.1
> 自己生成的和直接下载的配置都试过了，均无效… log 也都没有…
> 我就先留个爪，等等看其他人是什么情况…

1.模块是否生效？
不生效可以提交 xp 日志
2.日志记录是否成功？
提交模块记录的日志

**Comment by rambosir** [comment]
看来6.6.7-play版都有问题呀

**Comment by TTTPOB** [comment]
我这里也不能用诶也是play6.6.7生成下载都不行，看日志没有任何error， fail之类

**Comment by Blankeer** [comment]
> 我这里也不能用诶也是 play6.6.7 生成下载都不行，看日志没有任何 error， fail 之类

使用共享的配置呢？我自己测试play667是可以的

**Comment by Blankeer** [comment]
play 667有问题的重新下载共享的配置，刚刚更新了

**Comment by TTTPOB** [comment]
哇辛苦大大了，早点睡吧，都这么晚了

2018年9月18日 00:17，Blanke <notifications@github.com>写道：

play 667有问题的重新下载共享的配置，刚刚更新了

―

**Comment by TTTPOB** [comment]
啊啊然而我好像还是不行…会不会因为热更新啥的？

**Comment by jingyu9575** [comment]
3.2 / 6.6.7 PLAY / Android 8.1，在我这必须将配置重命名成 6.6.7-play.config 才有效。生成或下载的配置文件名都是 6.6.7.config。

[这里](https://github.com/Blankeer/MDWechat/blob/d6af3cbc5338ae3bb0e75436d0f1a86c6c2e96a5/app/src/main/java/com/blanke/mdwechat/config/AppCustomConfig.kt#L22)可能检查了1.x的Play版本开关，3.x无法设置此开关。因为这设置在SD卡和shared_prefs各有一份，所以单独卸载重装或删mdwechat目录都无法重置这个开关。同时卸载、删mdwechat目录可以解决。

建议去掉这个开关检查。

**Comment by TTTPOB** [comment]
十分感谢楼上…

**Comment by edison0354** [comment]
改名后可以了…感谢！

**Comment by Blankeer** [comment]
> 3.2 / 6.6.7 PLAY / Android 8.1，在我这必须将配置重命名成 6.6.7-play.config 才有效。生成或下载的配置文件名都是 6.6.7.config。
> 
> [这里](https://github.com/Blankeer/MDWechat/blob/d6af3cbc5338ae3bb0e75436d0f1a86c6c2e96a5/app/src/main/java/com/blanke/mdwechat/config/AppCustomConfig.kt#L22)可能检查了 1.x 的 Play 版本开关，3.x 无法设置此开关。因为这设置在 SD 卡和 shared_prefs 各有一份，所以单独卸载重装或删 mdwechat 目录都无法重置这个开关。同时卸载、删 mdwechat 目录可以解决。
> 
> 建议去掉这个开关检查。

感谢反馈！
已经[修复](https://github.com/Blankeer/MDWechat/commit/db396df7d87b93b3ac53d6fbed342a950b567056)该问题，下个版本生效。
目前该问题的解决方案是：卸载 MDWechat 重装并删除`/sdcard/mdwechat/config/md_wechat_settings.xml`即可解决
