### ISSUE TITLE
MDWechat 3.0.0依然出現一打開微信強制關閉的情況…

### ISSUE THREAD

**Issue by Darkpurple** [Blankeer/MDWechat#40]
已經按照升級說明重置所有東西，一打開微信馬上強制停止關閉
![screenshot_20180911-122816](https://user-images.githubusercontent.com/5692403/45338585-75d45c80-b5c0-11e8-85f0-8623c1459f7b.png)
![screenshot_20180911-124003](https://user-images.githubusercontent.com/5692403/45338595-7ff65b00-b5c0-11e8-8b1c-cdb245ffa0da.png)

。

环境

Android 版本8.1
机型 Oneplus 6
MDWechat 版本 3.0.0
Xposed 环境及版本 90.2beta3
微信版本 6.7.2

**Comment by Xiphoray** [comment]
![_20180912091426](https://user-images.githubusercontent.com/19776434/45396216-c1444480-b66c-11e8-80de-5aa43c97909c.jpg)


红米5plus同样问题

我同时有装微X模块，但禁用并没有带来改善

**Comment by Darkpurple** [comment]
我也把所有插件禁用掉…只用mdwechat還是一樣…一打開都是強制關閉…

升級了3.1.0問題還是沒改善……

**Comment by Blankeer** [comment]
不传日志的话，我是帮不了你的
