### ISSUE TITLE
3.0版本，微信6.7.2，选择移除顶部下拉小程序勾选时，微信顶部会多出一块灰色长方形区域。

### ISSUE THREAD

**Issue by gao410940747** [Blankeer/MDWechat#43]
移除顶部下拉小程序功能挺好用的。但是bug影响美观，希望解决，已捐赠，谢谢作者！

**Comment by gao410940747** [comment]
![_20180912145037](https://user-images.githubusercontent.com/43198424/45407170-362e7300-b69b-11e8-93c3-5b12a07e539f.png)

**Comment by gao410940747** [comment]
![_20180912145750](https://user-images.githubusercontent.com/43198424/45407493-282d2200-b69c-11e8-9cb2-f4a24ef98ba7.png)

**Comment by Blankeer** [comment]
3.1.0已修复
