### ISSUE TITLE
mdwechat3.1.0版本存在的bug

### ISSUE THREAD

**Issue by luoweij** [Blankeer/MDWechat#44]
第一不能进行全面屏效果设置，顶部出来黑色框
第二进入朋友状态栏不能进行变色，
不知道在哪上传图片。。。。。
只能这样用文字描述了。见谅。

**Comment by Blankeer** [comment]
第一个问题我已经说了，actionbar 和 tablayout 不能同时关闭
第二个问题，不是bug，设定如此
