### ISSUE TITLE
小米5，微信6.6.1无效

### ISSUE THREAD

**Issue by entalent** [Blankeer/MDWechat#5]
系统是魔趣的7.1.2，用自带的xposed框架，确定模块已经激活，总开关打开
开启圆角头像，按下波纹效果，ActionBar变色，状态栏全透明，TabLayout，TabLayout阴影，隐藏扫一扫/摇一摇/附近的人/购物选项，微信运行时没有任何效果

系统软重启之后的全部xposed日志：
01-09 01:50:12.783 I/Xposed  ( 6126): -----------------
01-09 01:50:12.783 I/Xposed  ( 6126): Starting Xposed version 89, compiled for SDK 25
01-09 01:50:12.783 I/Xposed  ( 6126): Device: MI 5 (Xiaomi), Android version 7.1.2 (SDK 25)
01-09 01:50:12.783 I/Xposed  ( 6126): ROM: mk_gemini-userdebug 7.1.2 NJH47F 516411c926 test-keys
01-09 01:50:12.783 I/Xposed  ( 6126): Build fingerprint: Xiaomi/gemini/gemini:7.0/NRD90M/V8.2.1.0.NAACNEB:user/release-keys
01-09 01:50:12.783 I/Xposed  ( 6126): Platform: arm64-v8a, 64-bit binary, system server: yes
01-09 01:50:12.783 I/Xposed  ( 6126): SELinux enabled: yes, enforcing: yes
01-09 01:50:13.869 I/Xposed  ( 6126): -----------------
01-09 01:50:13.869 I/Xposed  ( 6126): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
01-09 01:50:15.189 I/Xposed  ( 6126): Detected ART runtime
01-09 01:50:15.201 I/Xposed  ( 6126): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
01-09 01:50:15.456 I/Xposed  ( 6126): Loading modules from /data/app/com.blanke.mdwechat-1/base.apk
01-09 01:50:15.481 I/Xposed  ( 6126):   Loading class com.blanke.mdwechat.WechatHook
01-09 01:51:11.378 W/Xposed  ( 7793): Package name for /data/user/0/com.tencent.mm/tinker/patch-b8365d7d/res/resources.apk had to be retrieved via parser
01-09 01:55:04.493 W/Xposed  (11670): Package name for /data/user/0/com.tencent.mm/tinker/patch-b8365d7d/res/resources.apk had to be retrieved via parser

**Comment by Blankeer** [comment]
看日志,加载 mdwechat 正常,你贴下 mdwechat 相关的日志看看?
check list:
1.Xposed 是否正常 [√]
2.微信版本是否支持
3.安装后需要打开总功能开关,激活模块,重启手机.
4.以上还有问题,请提供 xposed 日志.
从第2项开始检查.
谢谢!

**Comment by entalent** [comment]
又试了一下……
只打开 ActionBar变色，状态栏全透明，TabLayout，TabLayout阴影，打开微信的时候只有状态栏的颜色变成主色，tablayout没有效果
微信客户端是在酷安安装的6.6.1版，应该没有问题

日志：
01-09 11:15:32.240 I/Xposed  (  650): -----------------
01-09 11:15:32.240 I/Xposed  (  650): Starting Xposed version 89, compiled for SDK 25
01-09 11:15:32.240 I/Xposed  (  650): Device: MI 5 (Xiaomi), Android version 7.1.2 (SDK 25)
01-09 11:15:32.240 I/Xposed  (  650): ROM: mk_gemini-userdebug 7.1.2 NJH47F 516411c926 test-keys
01-09 11:15:32.240 I/Xposed  (  650): Build fingerprint: Xiaomi/gemini/gemini:7.0/NRD90M/V8.2.1.0.NAACNEB:user/release-keys
01-09 11:15:32.240 I/Xposed  (  650): Platform: arm64-v8a, 64-bit binary, system server: yes
01-09 11:15:32.240 I/Xposed  (  650): SELinux enabled: yes, enforcing: yes
01-09 11:15:33.286 I/Xposed  (  650): -----------------
01-09 11:15:33.286 I/Xposed  (  650): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
01-09 11:15:34.383 I/Xposed  (  650): Detected ART runtime
01-09 11:15:34.396 I/Xposed  (  650): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
01-09 11:15:34.719 I/Xposed  (  650): Loading modules from /data/app/com.blanke.mdwechat-1/base.apk
01-09 11:15:34.747 I/Xposed  (  650):   Loading class com.blanke.mdwechat.WechatHook
01-09 11:15:42.830 I/Xposed  (  651): -----------------
01-09 11:15:42.830 I/Xposed  (  651): Starting Xposed version 89, compiled for SDK 25
01-09 11:15:42.830 I/Xposed  (  651): Device: MI 5 (Xiaomi), Android version 7.1.2 (SDK 25)
01-09 11:15:42.830 I/Xposed  (  651): ROM: mk_gemini-userdebug 7.1.2 NJH47F 516411c926 test-keys
01-09 11:15:42.831 I/Xposed  (  651): Build fingerprint: Xiaomi/gemini/gemini:7.0/NRD90M/V8.2.1.0.NAACNEB:user/release-keys
01-09 11:15:42.831 I/Xposed  (  651): Platform: arm64-v8a, 32-bit binary, system server: no
01-09 11:15:42.831 I/Xposed  (  651): SELinux enabled: yes, enforcing: yes
01-09 11:15:42.841 I/Xposed  (  651): -----------------
01-09 11:15:42.842 I/Xposed  (  651): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
01-09 11:15:43.411 I/Xposed  (  651): Detected ART runtime
01-09 11:15:43.421 I/Xposed  (  651): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
01-09 11:15:43.688 I/Xposed  (  651): Loading modules from /data/app/com.blanke.mdwechat-1/base.apk
01-09 11:15:43.707 I/Xposed  (  651):   Loading class com.blanke.mdwechat.WechatHook
01-09 11:15:58.453 I/Xposed  ( 2674): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm,MDWechat version=1.7.2	ts=1515467758453
01-09 11:15:58.520 I/Xposed  ( 2674): MDWechat:	支持该微信版本:6.6.1	ts=1515467758520
01-09 11:15:58.523 I/Xposed  ( 2674): MDWechat:	hook 开关:true	ts=1515467758523
01-09 11:16:06.378 I/Xposed  ( 3636): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm:exdevice,MDWechat version=1.7.2	ts=1515467766378
01-09 11:16:06.411 I/Xposed  ( 3636): MDWechat:	支持该微信版本:6.6.1	ts=1515467766411
01-09 11:16:06.006 I/Xposed  ( 3636): MDWechat:	hook 开关:true	ts=1515467766006
01-09 11:16:07.797 I/Xposed  ( 3719): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm:push,MDWechat version=1.7.2	ts=1515467767797
01-09 11:16:07.840 I/Xposed  ( 3719): MDWechat:	支持该微信版本:6.6.1	ts=1515467767840
01-09 11:16:07.847 I/Xposed  ( 3719): MDWechat:	hook 开关:true	ts=1515467767847
01-09 11:16:13.595 I/Xposed  ( 4020): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm:support,MDWechat version=1.7.2	ts=1515467773595
01-09 11:16:13.624 I/Xposed  ( 4020): MDWechat:	支持该微信版本:6.6.1	ts=1515467773624
01-09 11:16:13.627 I/Xposed  ( 4020): MDWechat:	hook 开关:true	ts=1515467773627
01-09 11:17:40.496 W/Xposed  ( 2674): Package name for /data/user/0/com.tencent.mm/tinker/patch-b8365d7d/res/resources.apk had to be retrieved via parser
01-09 11:17:41.679 I/Xposed  ( 5709): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm:appbrand0,MDWechat version=1.7.2	ts=1515467861679
01-09 11:17:41.702 I/Xposed  ( 5709): MDWechat:	支持该微信版本:6.6.1	ts=1515467861702
01-09 11:17:41.704 I/Xposed  ( 5709): MDWechat:	hook 开关:true	ts=1515467861704
01-09 11:17:46.376 I/Xposed  ( 5854): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm:tools,MDWechat version=1.7.2	ts=1515467866376
01-09 11:17:46.407 I/Xposed  ( 5854): MDWechat:	支持该微信版本:6.6.1	ts=1515467866407
01-09 11:17:46.409 I/Xposed  ( 5854): MDWechat:	hook 开关:true	ts=1515467866409
01-09 11:17:50.240 I/Xposed  ( 5973): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm:sandbox,MDWechat version=1.7.2	ts=1515467870240
01-09 11:17:50.264 I/Xposed  ( 5973): MDWechat:	支持该微信版本:6.6.1	ts=1515467870264
01-09 11:17:50.267 I/Xposed  ( 5973): MDWechat:	hook 开关:true	ts=1515467870267
01-09 11:18:19.726 I/Xposed  ( 6242): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm,MDWechat version=1.7.2	ts=1515467899726
01-09 11:18:19.743 I/Xposed  ( 6242): MDWechat:	支持该微信版本:6.6.1	ts=1515467899743
01-09 11:18:19.745 I/Xposed  ( 6242): MDWechat:	hook 开关:true	ts=1515467899745
01-09 11:18:22.020 W/Xposed  ( 6242): Package name for /data/user/0/com.tencent.mm/tinker/patch-b8365d7d/res/resources.apk had to be retrieved via parser
01-09 11:18:23.908 I/Xposed  ( 6310): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm:exdevice,MDWechat version=1.7.2	ts=1515467903908
01-09 11:18:23.927 I/Xposed  ( 6310): MDWechat:	支持该微信版本:6.6.1	ts=1515467903927
01-09 11:18:23.929 I/Xposed  ( 6310): MDWechat:	hook 开关:true	ts=1515467903929
01-09 11:18:25.516 I/Xposed  ( 6367): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm:push,MDWechat version=1.7.2	ts=1515467905516
01-09 11:18:25.558 I/Xposed  ( 6367): MDWechat:	支持该微信版本:6.6.1	ts=1515467905558
01-09 11:18:25.566 I/Xposed  ( 6367): MDWechat:	hook 开关:true	ts=1515467905566
01-09 11:18:27.817 I/Xposed  ( 6431): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm:appbrand0,MDWechat version=1.7.2	ts=1515467907817
01-09 11:18:27.841 I/Xposed  ( 6431): MDWechat:	支持该微信版本:6.6.1	ts=1515467907841
01-09 11:18:27.844 I/Xposed  ( 6431): MDWechat:	hook 开关:true	ts=1515467907844
01-09 11:18:31.202 I/Xposed  ( 6526): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm:support,MDWechat version=1.7.2	ts=1515467911202
01-09 11:18:31.227 I/Xposed  ( 6526): MDWechat:	支持该微信版本:6.6.1	ts=1515467911227
01-09 11:18:31.230 I/Xposed  ( 6526): MDWechat:	hook 开关:true	ts=1515467911230
01-09 11:18:33.433 I/Xposed  ( 6609): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm:tools,MDWechat version=1.7.2	ts=1515467913433
01-09 11:18:33.611 I/Xposed  ( 6609): MDWechat:	支持该微信版本:6.6.1	ts=1515467913611
01-09 11:18:33.619 I/Xposed  ( 6609): MDWechat:	hook 开关:true	ts=1515467913619
01-09 11:22:00.471 I/Xposed  ( 7517): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm,MDWechat version=1.7.2	ts=1515468120471
01-09 11:22:00.501 I/Xposed  ( 7517): MDWechat:	支持该微信版本:6.6.1	ts=1515468120501
01-09 11:22:00.504 I/Xposed  ( 7517): MDWechat:	hook 开关:true	ts=1515468120504
01-09 11:22:02.955 W/Xposed  ( 7517): Package name for /data/user/0/com.tencent.mm/tinker/patch-b8365d7d/res/resources.apk had to be retrieved via parser
01-09 11:22:04.893 I/Xposed  ( 7583): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm:exdevice,MDWechat version=1.7.2	ts=1515468124893
01-09 11:22:04.914 I/Xposed  ( 7583): MDWechat:	支持该微信版本:6.6.1	ts=1515468124914
01-09 11:22:04.916 I/Xposed  ( 7583): MDWechat:	hook 开关:true	ts=1515468124916
01-09 11:22:06.116 I/Xposed  ( 7631): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm:push,MDWechat version=1.7.2	ts=1515468126115
01-09 11:22:06.141 I/Xposed  ( 7631): MDWechat:	支持该微信版本:6.6.1	ts=1515468126141
01-09 11:22:06.144 I/Xposed  ( 7631): MDWechat:	hook 开关:true	ts=1515468126144
01-09 11:22:08.107 I/Xposed  ( 7697): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm:appbrand0,MDWechat version=1.7.2	ts=1515468128107
01-09 11:22:08.141 I/Xposed  ( 7697): MDWechat:	支持该微信版本:6.6.1	ts=1515468128141
01-09 11:22:08.144 I/Xposed  ( 7697): MDWechat:	hook 开关:true	ts=1515468128144
01-09 11:22:11.747 I/Xposed  ( 7812): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm:support,MDWechat version=1.7.2	ts=1515468131747
01-09 11:22:11.764 I/Xposed  ( 7812): MDWechat:	支持该微信版本:6.6.1	ts=1515468131764
01-09 11:22:11.766 I/Xposed  ( 7812): MDWechat:	hook 开关:true	ts=1515468131766
01-09 11:22:13.066 I/Xposed  ( 7864): MDWechat:	wechat version=6.6.1,processName=com.tencent.mm:tools,MDWechat version=1.7.2	ts=1515468133066
01-09 11:22:13.094 I/Xposed  ( 7864): MDWechat:	支持该微信版本:6.6.1	ts=1515468133094
01-09 11:22:13.099 I/Xposed  ( 7864): MDWechat:	hook 开关:true	ts=1515468133099

**Comment by Blankeer** [comment]
看日志貌似也没报错....
你可以先完全关闭微信(强行停止/最近任务划掉),并清除下 xp 日志,在 mdwechat 里重置下微信配置,然后重新打开微信,看看有没有问题,有问题再导出下日志.
一般这种情况(只有状态栏生效)的原因是,某个 hook 的地方找不到类/方法,导致后续 hook 失败,而修改状态栏颜色是调用的 android framework 的 api, 所以这里生效.

**Comment by entalent** [comment]
同样的机器和环境，退回到微信6.5.23和6.5.19版都一切正常（两个版本的微信都从酷安安装），只有6.6.1不正常，是对新版微信的适配有问题吗

**Comment by Blankeer** [comment]
尝试重新微信配置文件,我多测试下吧
因为我也是用的coolapk 6.6.1微信,没遇到这个问题.
你有抓到日志记得贴下.
谢谢
