### ISSUE TITLE
[3.1.0+6.6.5]联系人加载后Tab没有过渡动画

### ISSUE THREAD

**Issue by mochaaP** [Blankeer/MDWechat#50]
模块版本：3.1.0
微信版本：6.6.6 国内版
联系人加载后左右滑动Material Tabs的指示条过渡会消失。

**Comment by Blankeer** [comment]
由于你没有按照issues 模板提交，只能跟你这么说：
如果是在 vxp 环境，有几率出现这种情况。
如果是在真实环境，应该不会出现。
可以录制个gif 或者视频。
