### ISSUE TITLE
是不是修改了微信X5内核为本地浏览器内核？

### ISSUE THREAD

**Issue by rootdavid** [Blankeer/MDWechat#6]
浏览公众号评论样式出现布局错乱

**Comment by Blankeer** [comment]
😅这个还真没动过,这是所有[hook 的源码](https://github.com/Blankeer/MDWechat/tree/master/app/src/main/java/com/blanke/mdwechat/ui)

**Comment by rootdavid** [comment]
@Blankeer 打扰了 打扰了！原来是我以前的一个插件把微信的浏览内核给替换了。
解决方法：重新安装微信，再使用，就没问题了！谢谢你写的软件，UI真的漂亮！辛苦了！(*￣︶￣)
